"""executive_briefings + action_items + trend_alerts

Revision ID: 0021
Revises: 0020
Create Date: 2026-01-21 00:00:00

Sprint 8.3.10. Three new tables for the executive-tooling layer:

  1. ``executive_briefings`` — per-period summary rows generated by
     the LLM. Similar shape to ``strategic_reports`` but a separate
     table because the generation cadence and prompt context differ
     (week/month/quarter rolling, 12h cache).
  2. ``action_items`` — trackable tasks extracted from a SWOT
     report's strategic_recommendations or an executive briefing's
     top_actions, OR added manually. Carries status / priority /
     assignee / due_date for the kanban-style /action-items page.
  3. ``trend_alerts`` — threshold-based KPI deviation log. Manual
     evaluate trigger this sprint; cron arrives in Sprint 8.6
     alongside Prometheus.

RLS+FORCE on every table; same convention as 0006 / 0017 / 0019 / 0020.
``reviews.batch_job_id`` already exists (Sprint 8.3.1) so this
migration doesn't need to add it.

Forward-only — Sprint 8.3.5.2 dersi.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = "0021"
down_revision: str | Sequence[str] | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. executive_briefings -----------------------------------------------
    op.create_table(
        "executive_briefings",
        sa.Column(
            "id",
            PG_UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "tenant_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        # batch-scoped briefings carry the source batch id (NULL for
        # period-rolling briefings).
        sa.Column(
            "batch_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("analyze_batch_jobs.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column(
            "kpi_changes",
            JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "critical_insights",
            JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "top_actions",
            JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "input_stats",
            JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column(
            "token_usage", JSONB(), nullable=True
        ),
        sa.Column(
            "generation_duration_ms", sa.Integer(), nullable=True
        ),
        sa.Column(
            "created_by_user_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "period IN ('week', 'month', 'quarter')",
            name="ck_briefing_period",
        ),
    )
    op.create_index(
        "ix_executive_briefings_tenant_created",
        "executive_briefings",
        ["tenant_id", sa.text("created_at DESC")],
    )
    op.execute(
        "ALTER TABLE executive_briefings ENABLE ROW LEVEL SECURITY"
    )
    op.execute(
        "ALTER TABLE executive_briefings FORCE ROW LEVEL SECURITY"
    )
    op.execute(
        "CREATE POLICY tenant_isolation ON executive_briefings "
        "USING (tenant_id = current_setting('app.current_tenant_id')::uuid)"
    )

    # 2. action_items ------------------------------------------------------
    op.create_table(
        "action_items",
        sa.Column(
            "id",
            PG_UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "tenant_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "source_report_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("strategic_reports.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "source_briefing_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("executive_briefings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'medium'"),
        ),
        sa.Column(
            "estimated_impact",
            sa.String(length=16),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'open'"),
        ),
        sa.Column(
            "assignee_user_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "priority IN ('high', 'medium', 'low')",
            name="ck_action_items_priority",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'done', 'cancelled')",
            name="ck_action_items_status",
        ),
        sa.CheckConstraint(
            "estimated_impact IS NULL OR estimated_impact IN ("
            "'high', 'medium', 'low')",
            name="ck_action_items_estimated_impact",
        ),
        # An action item can come from at most one source — manual
        # creates leave both source_* fields NULL.
        sa.CheckConstraint(
            "NOT (source_report_id IS NOT NULL AND "
            "     source_briefing_id IS NOT NULL)",
            name="ck_action_items_one_source",
        ),
    )
    op.create_index(
        "ix_action_items_tenant_status",
        "action_items",
        ["tenant_id", "status"],
    )
    op.execute("ALTER TABLE action_items ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE action_items FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON action_items "
        "USING (tenant_id = current_setting('app.current_tenant_id')::uuid)"
    )

    # 3. trend_alerts ------------------------------------------------------
    op.create_table(
        "trend_alerts",
        sa.Column(
            "id",
            PG_UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "tenant_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # alert_type identifies the rule that triggered (e.g.
        # ``nps_drop_week`` / ``negative_sentiment_jump`` /
        # ``taxonomy_volume_spike``).
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        # Snapshot of the metric values that triggered the alert.
        sa.Column(
            "evidence",
            JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'active'"),
        ),
        sa.Column(
            "acknowledged_by_user_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name="ck_trend_alerts_severity",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'acknowledged', 'dismissed')",
            name="ck_trend_alerts_status",
        ),
    )
    op.create_index(
        "ix_trend_alerts_tenant_active",
        "trend_alerts",
        ["tenant_id", "status", sa.text("created_at DESC")],
    )
    op.execute("ALTER TABLE trend_alerts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE trend_alerts FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON trend_alerts "
        "USING (tenant_id = current_setting('app.current_tenant_id')::uuid)"
    )

    # 4. sla_rules CHECK update — accept slack_webhook + teams_webhook ---
    # Sprint 8.3.7 originally constrained action_type to four values;
    # webhook actions are wired in 8.3.10 and need to pass the CHECK.
    op.execute(
        "ALTER TABLE sla_rules DROP CONSTRAINT ck_sla_rules_action_type"
    )
    op.execute(
        "ALTER TABLE sla_rules ADD CONSTRAINT ck_sla_rules_action_type "
        "CHECK (action_type IN ("
        "'warn_only', 'create_ticket', 'escalate', 'notify_email', "
        "'slack_webhook', 'teams_webhook'))"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE sla_rules DROP CONSTRAINT ck_sla_rules_action_type"
    )
    op.execute(
        "ALTER TABLE sla_rules ADD CONSTRAINT ck_sla_rules_action_type "
        "CHECK (action_type IN ("
        "'warn_only', 'create_ticket', 'escalate', 'notify_email'))"
    )

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON trend_alerts")
    op.execute("ALTER TABLE trend_alerts DISABLE ROW LEVEL SECURITY")
    op.drop_index("ix_trend_alerts_tenant_active", table_name="trend_alerts")
    op.drop_table("trend_alerts")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON action_items")
    op.execute("ALTER TABLE action_items DISABLE ROW LEVEL SECURITY")
    op.drop_index("ix_action_items_tenant_status", table_name="action_items")
    op.drop_table("action_items")

    op.execute(
        "DROP POLICY IF EXISTS tenant_isolation ON executive_briefings"
    )
    op.execute(
        "ALTER TABLE executive_briefings DISABLE ROW LEVEL SECURITY"
    )
    op.drop_index(
        "ix_executive_briefings_tenant_created",
        table_name="executive_briefings",
    )
    op.drop_table("executive_briefings")
