"""Service layer: domain logic between FastAPI handlers and SQLAlchemy models."""

from imga_api.services.action_item_service import (
    ACTOR_BRIEFING_PIPELINE,
    ACTOR_LLM_EXTRACTION,
    ACTOR_SYSTEM,
    ACTOR_USER,
    ActionItemAlreadyArchived,
    ActionItemError,
    ActionItemNotArchived,
    ActionItemNotFound,
    ActionItemService,
)
from imga_api.services.analytics_service import (
    AnalyticsFilters,
    AnalyticsService,
)
from imga_api.services.audit_service import AuditService
from imga_api.services.auth_service import (
    AuthError,
    AuthService,
    TokenPair,
    TokenReuseDetectedError,
)
from imga_api.services.batch_service import (
    BatchAnalyzeService,
    BatchJobNotCancellableError,
    BatchJobNotFoundError,
    BatchProgress,
    BatchServiceError,
    QualityReportResponseInvalidError,
    QualityReportService,
)
from imga_api.services.comment_service import (
    MAX_BODY_LENGTH as COMMENT_MAX_BODY_LENGTH,
)
from imga_api.services.comment_service import (
    CommentForbiddenError,
    CommentNotFoundError,
    CommentService,
    CommentServiceError,
    TicketNotFoundForCommentError,
)
from imga_api.services.invitation_service import (
    INVITATION_TTL,
    InvitationAcceptanceError,
    InvitationEmailExistsError,
    InvitationEmailMismatchError,
    InvitationPreview,
    InvitationReauthFailedError,
    InvitationService,
)
from imga_api.services.briefing_schedule_service import (
    BriefingScheduleError,
    BriefingScheduleService,
    ScheduleNotFound,
    ScheduleSpec,
    compute_next_run_at,
)
from imga_api.services.decision_audit_service import (
    DECISION_ACTION_ITEM_ASSIGNED,
    DECISION_ACTION_ITEM_PRIORITY_CHANGED,
    DECISION_BRIEFING_ACKNOWLEDGED,
    DECISION_BRIEFING_DISMISSED,
    DECISION_KPI_GOAL_SET,
    DECISION_PROMPT_TEMPLATE_OVERRIDDEN,
    DECISION_SLA_RULE_CHANGED,
    DECISION_STRATEGIC_REPORT_APPROVED,
    DECISION_STRATEGIC_REPORT_REJECTED,
    DECISION_TENANT_SETTING_CHANGED,
    DECISION_WEBHOOK_DISPATCHED_MANUALLY,
    DecisionAuditService,
)
from imga_api.services.dimension_service import (
    DimensionBreakdown,
    DimensionConfigNotFound,
    DimensionError,
    DimensionService,
    UnknownDimension,
    compute_metric_by_dimension,
)
from imga_api.services.engagement_service import (
    DEFAULT_BANDS,
    EngagementError,
    EngagementRow,
    EngagementService,
    MonthlyMetricNotFound,
    normalize_month,
)
from imga_api.services.llm_audit_service import (
    CALL_TYPE_ACTION_EXTRACTION,
    CALL_TYPE_BRIEFING,
    CALL_TYPE_CLASSIFICATION,
    CALL_TYPE_OKR,
    CALL_TYPE_STRATEGIC_REPORT,
    LLMCallAuditor,
    LLMCallContext,
)
from imga_api.services.prompt_resolver import (
    MissingRequiredVariable,
    PromptResolver,
    PromptResolverError,
    PromptTemplateNotFound,
    ResolvedPrompt,
)
from imga_api.services.kpi_goal_service import (
    GoalAlreadyExists,
    GoalProgress,
    KpiGoalError,
    KpiGoalNotFound,
    KpiGoalService,
    UnknownMetricKey,
)
from imga_api.services.snapshot_service import (
    SnapshotPayload,
    SnapshotService,
)
from imga_api.services.report_service import (
    ReportEstimate,
    ReportExpiredError,
    ReportFilters,
    ReportInvalidFiltersError,
    ReportNotFoundError,
    ReportRequest,
    ReportService,
    ReportServiceError,
)
from imga_api.services.review_service import (
    DEDUP_WINDOW,
    CategoryNotConfiguredError,
    ReviewAlreadyTicketedError,
    ReviewBridgeResult,
    ReviewNotFoundError,
    ReviewService,
    ReviewServiceError,
)
from imga_api.services.tenant_config_service import (
    CategoryCodeArchivedError,
    CategoryCodeConflictError,
    CategoryNotFoundError,
    TenantConfigError,
    TenantConfigService,
)
from imga_api.services.tenant_service import (
    TenantNotFoundError,
    TenantService,
    TenantSlugTakenError,
)
from imga_api.services.ticket_filters import (
    GroupBy,
    OrderBy,
    OrderDirection,
    StatsRequest,
    TicketFilters,
)
from imga_api.services.ticket_service import (
    AutoCreateDecision,
    CancellationReasonRequiredError,
    DuplicateTicketError,
    TicketNotFoundError,
    TicketService,
    TicketServiceError,
    TicketStatsBucket,
    TicketStatsResult,
    TransitionRequest,
    UnclaimByOthersError,
    decide_auto_create_state,
)
from imga_api.services.ticket_state_machine import (
    ForbiddenTransitionError,
    InvalidTransitionError,
    WindowExpiredError,
)
from imga_api.services.user_service import TenantMember, UserService

__all__ = [
    "ACTOR_BRIEFING_PIPELINE",
    "ACTOR_LLM_EXTRACTION",
    "ACTOR_SYSTEM",
    "ACTOR_USER",
    "COMMENT_MAX_BODY_LENGTH",
    "DEDUP_WINDOW",
    "DEFAULT_BANDS",
    "INVITATION_TTL",
    "ActionItemAlreadyArchived",
    "ActionItemError",
    "ActionItemNotArchived",
    "ActionItemNotFound",
    "ActionItemService",
    "AnalyticsFilters",
    "AnalyticsService",
    "AuditService",
    "AuthError",
    "AuthService",
    "AutoCreateDecision",
    "BatchAnalyzeService",
    "BatchJobNotCancellableError",
    "BatchJobNotFoundError",
    "BatchProgress",
    "BatchServiceError",
    "CancellationReasonRequiredError",
    "CategoryCodeArchivedError",
    "CategoryCodeConflictError",
    "CategoryNotConfiguredError",
    "CategoryNotFoundError",
    "CommentForbiddenError",
    "CommentNotFoundError",
    "CommentService",
    "CommentServiceError",
    "DuplicateTicketError",
    "EngagementError",
    "EngagementRow",
    "EngagementService",
    "ForbiddenTransitionError",
    "GroupBy",
    "InvalidTransitionError",
    "BriefingScheduleError",
    "BriefingScheduleService",
    "GoalAlreadyExists",
    "GoalProgress",
    "InvitationAcceptanceError",
    "InvitationEmailExistsError",
    "InvitationEmailMismatchError",
    "InvitationPreview",
    "InvitationReauthFailedError",
    "InvitationService",
    "KpiGoalError",
    "KpiGoalNotFound",
    "KpiGoalService",
    "MonthlyMetricNotFound",
    "ScheduleNotFound",
    "ScheduleSpec",
    "SnapshotPayload",
    "SnapshotService",
    "UnknownMetricKey",
    "compute_next_run_at",
    "OrderBy",
    "OrderDirection",
    "QualityReportResponseInvalidError",
    "QualityReportService",
    "ReportEstimate",
    "ReportExpiredError",
    "ReportFilters",
    "ReportInvalidFiltersError",
    "ReportNotFoundError",
    "ReportRequest",
    "ReportService",
    "ReportServiceError",
    "ReviewAlreadyTicketedError",
    "ReviewBridgeResult",
    "ReviewNotFoundError",
    "ReviewService",
    "ReviewServiceError",
    "StatsRequest",
    "TenantConfigError",
    "TenantConfigService",
    "TenantMember",
    "TenantNotFoundError",
    "TenantService",
    "TenantSlugTakenError",
    "TicketFilters",
    "TicketNotFoundError",
    "TicketNotFoundForCommentError",
    "TicketService",
    "TicketServiceError",
    "TicketStatsBucket",
    "TicketStatsResult",
    "TokenPair",
    "TokenReuseDetectedError",
    "TransitionRequest",
    "UnclaimByOthersError",
    "UserService",
    "WindowExpiredError",
    "decide_auto_create_state",
    "normalize_month",
]
